# Allows players to break blocks in others' claims
can-break-in-others-claims: true

blacklisted-claim-blocks:
- PISTON
- OBSERVER
- DISPENSER
- HOPPER
- DROPPER
- CHEST
- TRAPPED_CHEST
- REDSTONE_WIRE
- REDSTONE_WALL_TORCH
- REDSTONE_BLOCK
- REPEATER
- COMPARATOR
- REDSTONE_TORCH
- RAIL
- POWERED_RAIL
- DETECTOR_RAIL
- ACTIVATOR_RAIL
- LEVER
- TRIPWIRE_HOOK
- NOTE_BLOCK
- LIGHT_WEIGHTED_PRESSURE_PLATE
- STONE_PRESSURE_PLATE
- OAK_PRESSURE_PLATE
- SPRUCE_PRESSURE_PLATE
- BIRCH_PRESSURE_PLATE
- JUNGLE_PRESSURE_PLATE
- ACACIA_PRESSURE_PLATE
- DARK_OAK_PRESSURE_PLATE
- CRIMSON_PRESSURE_PLATE
- WARPED_PRESSURE_PLATE
- POLISHED_BLACKSTONE_PRESSURE_PLATE
- HEAVY_WEIGHTED_PRESSURE_PLATE
- STONE_BUTTON
- OAK_BUTTON
- SPRUCE_BUTTON
- BIRCH_BUTTON
- JUNGLE_BUTTON
- ACACIA_BUTTON
- DARK_OAK_BUTTON
- CRIMSON_BUTTON
- WARPED_BUTTON
- POLISHED_BLACKSTONE_BUTTON
- BANNER
- WHITE_BANNER
- ORANGE_BANNER
- MAGENTA_BANNER
- LIGHT_BLUE_BANNER
- YELLOW_BANNER
- LIME_BANNER
- PINK_BANNER
- GRAY_BANNER
- PINK_BANNER
- GRAY_BANNER
- LIGHT_GRAY_BANNER
- CYAN_BANNER
- PURPLE_BANNER
- BLUE_BANNER
- BROWN_BANNER
- GREEN_BANNER
- RED_BANNER
- BLACK_BANNER
- WHITE_WALL_BANNER
- ORANGE_WALL_BANNER
- MAGENTA_WALL_BANNER
- LIGHT_BLUE_WALL_BANNER
- YELLOW_WALL_BANNER
- LIME_WALL_BANNER
- PINK_WALL_BANNER
- GRAY_WALL_BANNER
- PINK_WALL_BANNER
- GRAY_WALL_BANNER
- LIGHT_GRAY_WALL_BANNER
- CYAN_WALL_BANNER
- PURPLE_WALL_BANNER
- BLUE_WALL_BANNER
- BROWN_WALL_BANNER
- GREEN_WALL_BANNER
- RED_WALL_BANNER
- BLACK_WALL_BANNER
- GOLD_BLOCK
- DIAMOND_BLOCK
- EMERALD_BLOCK
- ENCHANTING_TABLE
- NETHERITE_BLOCK
- ZOMBIE_HEAD
- PLAYER_HEAD
- DRAGON_HEAD
- CREEPER_HEAD
- SKELETON_SKULL
- WITHER_SKELETON_SKULL
- ZOMBIE_WALL_HEAD
- PLAYER_WALL_HEAD
- DRAGON_WALL_HEAD
- CREEPER_WALL_HEAD
- SKELETON_WALL_SKULL
- WITHER_SKELETON_WALL_SKULL
- BEEHIVE
- ACACIA_SIGN
- ACACIA_WALL_SIGN
- BIRCH_SIGN
- BIRCH_WALL_SIGN
- CRIMSON_SIGN
- CRIMSON_WALL_SIGN
- DARK_OAK_SIGN
- DARK_OAK_WALL_SIGN
- JUNGLE_SIGN
- JUNGLE_WALL_SIGN
- OAK_SIGN
- OAK_WALL_SIGN
- SPRUCE_SIGN
- SPRUCE_WALL_SIGN
- WARPED_SIGN
- WARPED_WALL_SIGN

blacklisted-blocks:
- CRIMSON_NYLIUM
- WARPED_NYLIUM
- ANDESITE
- SCAFFOLDING
- FIRE
- POTATOES
- LECTERN
- COBWEB
- SNOW
- GRASS
- FERN
- TALL_GRASS
- SEAGRASS
- TALL_SEAGRASS
- LARGE_FERN
- WHEAT
- SUGAR_CANE
- KELP
- KELP_PLANT
- CRAFTING_TABLE
- FURNACE
- BLAST_FURNACE
- SMOKER
- ENDER_CHEST
- MINECART
- CHEST_MINECART
- FURNACE_MINECART
- HOPPER_MINECART
- WHITE_SHULKER_BOX
- ORANGE_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- LIGHT_BLUE_SHULKER_BOX
- YELLOW_SHULKER_BOX
- LIME_SHULKER_BOX
- PINK_SHULKER_BOX
- GRAY_SHULKER_BOX
- LIGHT_GRAY_SHULKER_BOX
- CYAN_SHULKER_BOX
- PURPLE_SHULKER_BOX
- BLUE_SHULKER_BOX
- BROWN_SHULKER_BOX
- GREEN_SHULKER_BOX
- RED_SHULKER_BOX
- SHULKER_BOX
- TORCH
- SOUL_TORCH
- WALL_TORCH
- SOUL_WALL_TORCH
- BELL
- BEE_NEST
- OAK_BOAT
- SPRUCE_BOAT
- BIRCH_BOAT
- JUNGLE_BOAT
- ACACIA_BOAT
- DARK_OAK_BOAT
- BOAT
- OAK_SAPLING
- SPRUCE_SAPLING
- BIRCH_SAPLING
- JUNGLE_SAPLING
- ACACIA_SAPLING
- DARK_OAK_SAPLING
- WHITE_BED
- ORANGE_BED
- MAGENTA_BED
- LIGHT_BLUE_BED
- YELLOW_BED
- LIME_BED
- PINK_BED
- GRAY_BED
- LIGHT_GRAY_BED
- CYAN_BED
- PURPLE_BED
- BLUE_BED
- BROWN_BED
- GREEN_BED
- RED_BED
- BLACK_BED
- BED
- REDSTONE_ORE
- NETHER_GOLD_ORE
- NETHER_QUARTZ_ORE
- LAPIS_ORE
- IRON_ORE
- GOLD_ORE
- EMERALD_ORE
- DIAMOND_ORE
- DEEPSLATE_LAPIS_ORE
- DEEPSLATE_REDSTONE_ORE
- DEEPSLATE_COAL_ORE
- DEEPSLATE_COPPER_ORE
- DEEPSLATE_DIAMOND_ORE
- DEEPSLATE_EMERALD_ORE
- DEEPSLATE_GOLD_ORE
- DEEPSLATE_IRON_ORE
- COPPER_ORE
- COAL_ORE
- ANCIENT_DEBRIS
- DEAD_BUSH
- LADDER
- PAINTING
- SPAWNER
- OAK_LOG
- SPRUCE_LOG
- BIRCH_LOG
- JUNGLE_LOG
- ACACIA_LOG
- DARK_OAK_LOG
- STRIPPED_OAK_LOG
- STRIPPED_SPRUCE_LOG
- STRIPPED_BIRCH_LOG
- STRIPPED_JUNGLE_LOG
- STRIPPED_ACACIA_LOG
- STRIPPED_DARK_OAK_LOG
- OAK_LEAVES
- SPRUCE_LEAVES
- BIRCH_LEAVES
- JUNGLE_LEAVES
- ACACIA_LEAVES
- DARK_OAK_LEAVES
- COCOA
- VINE
- MELON_STEM
- ATTACHED_MELON_STEM
- PUMPKIN_STEM
- ATTACHED_PUMPKIN_STEM

no-loot-on-break:
- ACACIA_BUTTON
- ACACIA_DOOR
- ACACIA_FENCE
- ACACIA_FENCE_GATE
- ACACIA_PLANKS
- ACACIA_PRESSURE_PLATE
- ACACIA_SIGN
- ACACIA_WALL_SIGN
- ACACIA_SLAB
- ACACIA_STAIRS
- ACACIA_TRAPDOOR
- ACACIA_WOOD
- ALLIUM
- ANDESITE_SLAB
- ANDESITE_STAIRS
- ANDESITE_WALL
- ANVIL
- ARMOR_STAND
- AZURE_BLUET
- BAMBOO
- BAMBOO_SAPLING
- BARREL
- BARRIER
- BASALT
- BEDROCK
- BEEHIVE
- BIG_DRIPLEAF
- BIRCH_BUTTON
- BIRCH_DOOR
- BIRCH_FENCE
- BIRCH_FENCE_GATE
- BIRCH_PLANKS
- BIRCH_PRESSURE_PLATE
- BIRCH_SIGN
- BIRCH_WALL_SIGN
- BIRCH_SLAB
- BIRCH_STAIRS
- BIRCH_TRAPDOOR
- BIRCH_WOOD
- BLACKSTONE
- BLACKSTONE_SLAB
- BLACKSTONE_STAIRS
- BLACKSTONE_WALL
- BLACK_CARPET
- BLACK_CONCRETE
- BLACK_CONCRETE_POWDER
- BLACK_GLAZED_TERRACOTTA
- BLACK_STAINED_GLASS
- BLACK_STAINED_GLASS_PANE
- BLACK_TERRACOTTA
- BLACK_WOOL
- BLAZE_ROD
- BLUE_CARPET
- BLUE_CONCRETE
- BLUE_CONCRETE_POWDER
- BLUE_GLAZED_TERRACOTTA
- BLUE_ICE
- BLUE_ORCHID
- BLUE_STAINED_GLASS
- BLUE_STAINED_GLASS_PANE
- BLUE_TERRACOTTA
- BLUE_WOOL
- BONE_BLOCK
- BOOKSHELF
- BRAIN_CORAL
- BRAIN_CORAL_BLOCK
- BRAIN_CORAL_FAN
- BRAIN_CORAL_WALL_FAN
- BREWING_STAND
- BRICKS
- BRICK_SLAB
- BRICK_STAIRS
- BRICK_WALL
- BROWN_CARPET
- BROWN_CONCRETE
- BROWN_CONCRETE_POWDER
- BROWN_GLAZED_TERRACOTTA
- BROWN_MUSHROOM_BLOCK
- BROWN_STAINED_GLASS
- BROWN_STAINED_GLASS_PANE
- BROWN_TERRACOTTA
- BROWN_WOOL
- BUBBLE_CORAL
- BUBBLE_CORAL_BLOCK
- BUBBLE_CORAL_FAN
- BUBBLE_CORAL_WALL_FAN
- BUDDING_AMETHYST
- CALCITE
- CAMPFIRE
- CARTOGRAPHY_TABLE
- CARVED_PUMPKIN
- CAULDRON
- CHAIN
- CHIPPED_ANVIL
- CHISELED_DEEPSLATE
- CHISELED_NETHER_BRICKS
- CHISELED_POLISHED_BLACKSTONE
- CHISELED_QUARTZ_BLOCK
- CHISELED_RED_SANDSTONE
- CHISELED_SANDSTONE
- CHISELED_STONE_BRICKS
- CHORUS_FLOWER
- CHORUS_PLANT
- COAL_BLOCK
- COARSE_DIRT
- COBBLED_DEEPSLATE
- COBBLED_DEEPSLATE_SLAB
- COBBLED_DEEPSLATE_STAIRS
- COBBLED_DEEPSLATE_WALL
- COBBLESTONE
- COBBLESTONE_SLAB
- COBBLESTONE_STAIRS
- COBBLESTONE_WALL
- COMPOSTER
- CONDUIT
- COPPER_BLOCK
- CORNFLOWER
- CRACKED_DEEPSLATE_BRICKS
- CRACKED_DEEPSLATE_TILES
- CRACKED_NETHER_BRICKS
- CRACKED_POLISHED_BLACKSTONE_BRICKS
- CRACKED_STONE_BRICKS
- CRIMSON_BUTTON
- CRIMSON_DOOR
- CRIMSON_FENCE
- CRIMSON_FENCE_GATE
- CRIMSON_FUNGUS
- CRIMSON_HYPHAE
- CRIMSON_NYLIUM
- CRIMSON_PLANKS
- CRIMSON_PRESSURE_PLATE
- CRIMSON_ROOTS
- CRIMSON_SIGN
- CRIMSON_WALL_SIGN
- CRIMSON_SLAB
- CRIMSON_STAIRS
- CRIMSON_STEM
- CRIMSON_TRAPDOOR
- CRYING_OBSIDIAN
- CUT_COPPER
- CUT_COPPER_SLAB
- CUT_COPPER_STAIRS
- CUT_RED_SANDSTONE
- CUT_RED_SANDSTONE_SLAB
- CUT_SANDSTONE
- CUT_SANDSTONE_SLAB
- CYAN_CARPET
- CYAN_CONCRETE
- CYAN_CONCRETE_POWDER
- CYAN_GLAZED_TERRACOTTA
- CYAN_STAINED_GLASS
- CYAN_STAINED_GLASS_PANE
- CYAN_TERRACOTTA
- CYAN_WOOL
- DAMAGED_ANVIL
- DANDELION
- DARK_OAK_BUTTON
- DARK_OAK_DOOR
- DARK_OAK_FENCE
- DARK_OAK_FENCE_GATE
- DARK_OAK_PLANKS
- DARK_OAK_PRESSURE_PLATE
- DARK_OAK_SIGN
- DARK_OAK_WALL_SIGN
- DARK_OAK_SLAB
- DARK_OAK_STAIRS
- DARK_OAK_TRAPDOOR
- DARK_OAK_WOOD
- DARK_PRISMARINE
- DARK_PRISMARINE_SLAB
- DARK_PRISMARINE_STAIRS
- DAYLIGHT_DETECTOR
- DEAD_BRAIN_CORAL
- DEAD_BRAIN_CORAL_BLOCK
- DEAD_BRAIN_CORAL_FAN
- DEAD_BRAIN_CORAL_WALL_FAN
- DEAD_BUBBLE_CORAL
- DEAD_BUBBLE_CORAL_BLOCK
- DEAD_BUBBLE_CORAL_FAN
- DEAD_BUBBLE_CORAL_WALL_FAN
- DEAD_FIRE_CORAL
- DEAD_FIRE_CORAL_BLOCK
- DEAD_FIRE_CORAL_FAN
- DEAD_FIRE_CORAL_WALL_FAN
- DEAD_HORN_CORAL
- DEAD_HORN_CORAL_BLOCK
- DEAD_HORN_CORAL_FAN
- DEAD_HORN_CORAL_WALL_FAN
- DEAD_TUBE_CORAL
- DEAD_TUBE_CORAL_BLOCK
- DEAD_TUBE_CORAL_FAN
- DEAD_TUBE_CORAL_WALL_FAN
- DEBUG_STICK
- DEEPSLATE
- DEEPSLATE_BRICKS
- DEEPSLATE_BRICK_SLAB
- DEEPSLATE_BRICK_STAIRS
- DEEPSLATE_BRICK_WALL
- DEEPSLATE_TILES
- DEEPSLATE_TILE_SLAB
- DEEPSLATE_TILE_STAIRS
- DEEPSLATE_TILE_WALL
- DIORITE
- DIORITE_SLAB
- DIORITE_STAIRS
- DIORITE_WALL
- DIRT
- DIRT_PATH
- DRIED_KELP_BLOCK
- DRIPSTONE_BLOCK
- END_PORTAL_FRAME
- END_ROD
- END_STONE
- END_STONE_BRICKS
- END_STONE_BRICK_SLAB
- END_STONE_BRICK_STAIRS
- END_STONE_BRICK_WALL
- EXPOSED_COPPER
- EXPOSED_CUT_COPPER
- EXPOSED_CUT_COPPER_SLAB
- EXPOSED_CUT_COPPER_STAIRS
- FARMLAND
- FIRE_CORAL
- FIRE_CORAL_BLOCK
- FIRE_CORAL_FAN
- FIRE_CORAL_WALL_FAN
- FLETCHING_TABLE
- FLOWERING_AZALEA
- FLOWER_POT
- GILDED_BLACKSTONE
- GLASS
- GLASS_PANE
- GLOWSTONE
- GLOW_BERRIES
- GLOW_INK_SAC
- GLOW_ITEM_FRAME
- GLOW_LICHEN
- GRANITE
- GRANITE_SLAB
- GRANITE_STAIRS
- GRANITE_WALL
- GRASS_BLOCK
- GRAVEL
- GRAY_CARPET
- GRAY_CONCRETE
- GRAY_CONCRETE_POWDER
- GRAY_GLAZED_TERRACOTTA
- GRAY_STAINED_GLASS
- GRAY_STAINED_GLASS_PANE
- GRAY_TERRACOTTA
- GRAY_WOOL
- GREEN_CARPET
- GREEN_CONCRETE
- GREEN_CONCRETE_POWDER
- GREEN_GLAZED_TERRACOTTA
- GREEN_STAINED_GLASS
- GREEN_STAINED_GLASS_PANE
- GREEN_TERRACOTTA
- GREEN_WOOL
- GRINDSTONE
- HANGING_ROOTS
- HAY_BLOCK
- HEAVY_WEIGHTED_PRESSURE_PLATE
- HONEYCOMB
- HONEYCOMB_BLOCK
- HONEY_BLOCK
- HORN_CORAL
- HORN_CORAL_BLOCK
- HORN_CORAL_FAN
- HORN_CORAL_WALL_FAN
- ICE
- INFESTED_CHISELED_STONE_BRICKS
- INFESTED_COBBLESTONE
- INFESTED_CRACKED_STONE_BRICKS
- INFESTED_DEEPSLATE
- INFESTED_MOSSY_STONE_BRICKS
- INFESTED_STONE
- INFESTED_STONE_BRICKS
- IRON_BLOCK
- IRON_DOOR
- IRON_TRAPDOOR
- ITEM_FRAME
- JACK_O_LANTERN
- JIGSAW
- JUKEBOX
- JUNGLE_BUTTON
- JUNGLE_DOOR
- JUNGLE_FENCE
- JUNGLE_FENCE_GATE
- JUNGLE_PLANKS
- JUNGLE_PRESSURE_PLATE
- JUNGLE_SIGN
- JUNGLE_WALL_SIGN
- JUNGLE_SLAB
- JUNGLE_STAIRS
- JUNGLE_TRAPDOOR
- JUNGLE_WOOD
- LANTERN
- LAPIS_BLOCK
- LARGE_AMETHYST_BUD
- LEVER
- LIGHT
- LIGHTNING_ROD
- LIGHT_BLUE_CARPET
- LIGHT_BLUE_CONCRETE
- LIGHT_BLUE_CONCRETE_POWDER
- LIGHT_BLUE_GLAZED_TERRACOTTA
- LIGHT_BLUE_STAINED_GLASS
- LIGHT_BLUE_STAINED_GLASS_PANE
- LIGHT_BLUE_TERRACOTTA
- LIGHT_BLUE_WOOL
- LIGHT_GRAY_CARPET
- LIGHT_GRAY_CONCRETE
- LIGHT_GRAY_CONCRETE_POWDER
- LIGHT_GRAY_GLAZED_TERRACOTTA
- LIGHT_GRAY_STAINED_GLASS
- LIGHT_GRAY_STAINED_GLASS_PANE
- LIGHT_GRAY_TERRACOTTA
- LIGHT_GRAY_WOOL
- LIGHT_WEIGHTED_PRESSURE_PLATE
- LILAC
- LILY_OF_THE_VALLEY
- LILY_PAD
- LIME_CARPET
- LIME_CONCRETE
- LIME_CONCRETE_POWDER
- LIME_GLAZED_TERRACOTTA
- LIME_STAINED_GLASS
- LIME_STAINED_GLASS_PANE
- LIME_TERRACOTTA
- LIME_WOOL
- LODESTONE
- LOOM
- MAGENTA_CARPET
- MAGENTA_CONCRETE
- MAGENTA_CONCRETE_POWDER
- MAGENTA_GLAZED_TERRACOTTA
- MAGENTA_STAINED_GLASS
- MAGENTA_STAINED_GLASS_PANE
- MAGENTA_TERRACOTTA
- MAGENTA_WOOL
- MAGMA_BLOCK
- MAGMA_CREAM
- MEDIUM_AMETHYST_BUD
- MELON
- MELON_SLICE
- MOSSY_COBBLESTONE
- MOSSY_COBBLESTONE_SLAB
- MOSSY_COBBLESTONE_STAIRS
- MOSSY_COBBLESTONE_WALL
- MOSSY_STONE_BRICKS
- MOSSY_STONE_BRICK_SLAB
- MOSSY_STONE_BRICK_STAIRS
- MOSSY_STONE_BRICK_WALL
- MOSS_BLOCK
- MOSS_CARPET
- MUSHROOM_STEM
- MUSHROOM_STEW
- MUTTON
- MYCELIUM
- NETHERRACK
- NETHER_BRICK
- NETHER_BRICKS
- NETHER_BRICK_FENCE
- NETHER_BRICK_SLAB
- NETHER_BRICK_STAIRS
- NETHER_BRICK_WALL
- NETHER_SPROUTS
- NETHER_STAR
- NETHER_WART
- NETHER_WART_BLOCK
- OAK_BUTTON
- OAK_DOOR
- OAK_FENCE
- OAK_FENCE_GATE
- OAK_PLANKS
- OAK_PRESSURE_PLATE
- OAK_SIGN
- OAK_WALL_SIGN
- OAK_SLAB
- OAK_STAIRS
- OAK_TRAPDOOR
- OAK_WOOD
- OBSERVER
- OBSIDIAN
- ORANGE_CARPET
- ORANGE_CONCRETE
- ORANGE_CONCRETE_POWDER
- ORANGE_GLAZED_TERRACOTTA
- ORANGE_STAINED_GLASS
- ORANGE_STAINED_GLASS_PANE
- ORANGE_TERRACOTTA
- ORANGE_TULIP
- ORANGE_WOOL
- OXEYE_DAISY
- OXIDIZED_COPPER
- OXIDIZED_CUT_COPPER
- OXIDIZED_CUT_COPPER_SLAB
- OXIDIZED_CUT_COPPER_STAIRS
- PACKED_ICE
- PEONY
- PETRIFIED_OAK_SLAB
- PINK_CARPET
- PINK_CONCRETE
- PINK_CONCRETE_POWDER
- PINK_GLAZED_TERRACOTTA
- PINK_STAINED_GLASS
- PINK_STAINED_GLASS_PANE
- PINK_TERRACOTTA
- PINK_TULIP
- PINK_WOOL
- PISTON
- PODZOL
- POINTED_DRIPSTONE
- POLISHED_ANDESITE
- POLISHED_ANDESITE_SLAB
- POLISHED_ANDESITE_STAIRS
- POLISHED_BASALT
- POLISHED_BLACKSTONE
- POLISHED_BLACKSTONE_BRICKS
- POLISHED_BLACKSTONE_BRICK_SLAB
- POLISHED_BLACKSTONE_BRICK_STAIRS
- POLISHED_BLACKSTONE_BRICK_WALL
- POLISHED_BLACKSTONE_BUTTON
- POLISHED_BLACKSTONE_PRESSURE_PLATE
- POLISHED_BLACKSTONE_SLAB
- POLISHED_BLACKSTONE_STAIRS
- POLISHED_BLACKSTONE_WALL
- POLISHED_DEEPSLATE
- POLISHED_DEEPSLATE_SLAB
- POLISHED_DEEPSLATE_STAIRS
- POLISHED_DEEPSLATE_WALL
- POLISHED_DIORITE
- POLISHED_DIORITE_SLAB
- POLISHED_DIORITE_STAIRS
- POLISHED_GRANITE
- POLISHED_GRANITE_SLAB
- POLISHED_GRANITE_STAIRS
- POPPY
- PRISMARINE
- PRISMARINE_BRICKS
- PRISMARINE_BRICK_SLAB
- PRISMARINE_BRICK_STAIRS
- PRISMARINE_CRYSTALS
- PRISMARINE_SHARD
- PRISMARINE_SLAB
- PRISMARINE_STAIRS
- PRISMARINE_WALL
- PUMPKIN
- PURPLE_CARPET
- PURPLE_CONCRETE
- PURPLE_CONCRETE_POWDER
- PURPLE_GLAZED_TERRACOTTA
- PURPLE_STAINED_GLASS
- PURPLE_STAINED_GLASS_PANE
- PURPLE_TERRACOTTA
- PURPLE_WOOL
- PURPUR_BLOCK
- PURPUR_PILLAR
- PURPUR_SLAB
- PURPUR_STAIRS
- QUARTZ
- QUARTZ_BLOCK
- QUARTZ_BRICKS
- QUARTZ_PILLAR
- QUARTZ_SLAB
- QUARTZ_STAIRS
- RAW_COPPER
- RAW_COPPER_BLOCK
- RAW_GOLD
- RAW_GOLD_BLOCK
- RAW_IRON
- RAW_IRON_BLOCK
- REDSTONE_BLOCK
- REDSTONE_LAMP
- RED_CARPET
- RED_CONCRETE
- RED_CONCRETE_POWDER
- RED_GLAZED_TERRACOTTA
- RED_MUSHROOM_BLOCK
- RED_NETHER_BRICKS
- RED_NETHER_BRICK_SLAB
- RED_NETHER_BRICK_STAIRS
- RED_NETHER_BRICK_WALL
- RED_SAND
- RED_SANDSTONE
- RED_SANDSTONE_SLAB
- RED_SANDSTONE_STAIRS
- RED_SANDSTONE_WALL
- RED_STAINED_GLASS
- RED_STAINED_GLASS_PANE
- RED_TERRACOTTA
- RED_TULIP
- RED_WOOL
- REPEATING_COMMAND_BLOCK
- RESPAWN_ANCHOR
- ROOTED_DIRT
- ROSE_BUSH
- SAND
- SANDSTONE
- SANDSTONE_SLAB
- SANDSTONE_STAIRS
- SANDSTONE_WALL
- SCULK_SENSOR
- SCUTE
- SEA_LANTERN
- SEA_PICKLE
- SHROOMLIGHT
- SLIME_BLOCK
- SMALL_AMETHYST_BUD
- SMALL_DRIPLEAF
- SMITHING_TABLE
- SMOOTH_BASALT
- SMOOTH_QUARTZ
- SMOOTH_QUARTZ_SLAB
- SMOOTH_QUARTZ_STAIRS
- SMOOTH_RED_SANDSTONE
- SMOOTH_RED_SANDSTONE_SLAB
- SMOOTH_RED_SANDSTONE_STAIRS
- SMOOTH_SANDSTONE
- SMOOTH_SANDSTONE_SLAB
- SMOOTH_SANDSTONE_STAIRS
- SMOOTH_STONE
- SMOOTH_STONE_SLAB
- SNOW_BLOCK
- SOUL_CAMPFIRE
- SOUL_LANTERN
- SOUL_SAND
- SOUL_SOIL
- SPONGE
- SPORE_BLOSSOM
- SPRUCE_BUTTON
- SPRUCE_DOOR
- SPRUCE_FENCE
- SPRUCE_FENCE_GATE
- SPRUCE_PLANKS
- SPRUCE_PRESSURE_PLATE
- SPRUCE_SIGN
- SPRUCE_WALL_SIGN
- SPRUCE_SLAB
- SPRUCE_STAIRS
- SPRUCE_TRAPDOOR
- SPRUCE_WOOD
- STICKY_PISTON
- STONECUTTER
- STONE_BRICKS
- STONE_BRICK_SLAB
- STONE_BRICK_STAIRS
- STONE_BRICK_WALL
- STONE_BUTTON
- STONE_PRESSURE_PLATE
- STONE_SLAB
- STONE_STAIRS
- STRIPPED_ACACIA_LOG
- STRIPPED_ACACIA_WOOD
- STRIPPED_BIRCH_LOG
- STRIPPED_BIRCH_WOOD
- STRIPPED_CRIMSON_HYPHAE
- STRIPPED_CRIMSON_STEM
- STRIPPED_DARK_OAK_LOG
- STRIPPED_DARK_OAK_WOOD
- STRIPPED_JUNGLE_LOG
- STRIPPED_JUNGLE_WOOD
- STRIPPED_OAK_LOG
- STRIPPED_OAK_WOOD
- STRIPPED_SPRUCE_LOG
- STRIPPED_SPRUCE_WOOD
- STRIPPED_WARPED_HYPHAE
- STRIPPED_WARPED_STEM
- STRUCTURE_BLOCK
- STRUCTURE_VOID
- SUNFLOWER
- TARGET
- TERRACOTTA
- TINTED_GLASS
- TNT
- TROPICAL_FISH
- TUBE_CORAL
- TUBE_CORAL_BLOCK
- TUBE_CORAL_FAN
- TUBE_CORAL_WALL_FAN
- TUFF
- TWISTING_VINES
- VINE
- WARPED_BUTTON
- WARPED_DOOR
- WARPED_FENCE
- WARPED_FENCE_GATE
- WARPED_FUNGUS
- WARPED_FUNGUS_ON_A_STICK
- WARPED_HYPHAE
- WARPED_NYLIUM
- WARPED_PLANKS
- WARPED_PRESSURE_PLATE
- WARPED_ROOTS
- WARPED_SIGN
- WARPED_WALL_SIGN
- WARPED_SLAB
- WARPED_STAIRS
- WARPED_STEM
- WARPED_TRAPDOOR
- WARPED_WART_BLOCK
- WAXED_COPPER_BLOCK
- WAXED_CUT_COPPER
- WAXED_CUT_COPPER_SLAB
- WAXED_CUT_COPPER_STAIRS
- WAXED_EXPOSED_COPPER
- WAXED_EXPOSED_CUT_COPPER
- WAXED_EXPOSED_CUT_COPPER_SLAB
- WAXED_EXPOSED_CUT_COPPER_STAIRS
- WAXED_OXIDIZED_COPPER
- WAXED_OXIDIZED_CUT_COPPER
- WAXED_OXIDIZED_CUT_COPPER_SLAB
- WAXED_OXIDIZED_CUT_COPPER_STAIRS
- WAXED_WEATHERED_COPPER
- WAXED_WEATHERED_CUT_COPPER
- WAXED_WEATHERED_CUT_COPPER_SLAB
- WAXED_WEATHERED_CUT_COPPER_STAIRS
- WEATHERED_COPPER
- WEATHERED_CUT_COPPER
- WEATHERED_CUT_COPPER_SLAB
- WEATHERED_CUT_COPPER_STAIRS
- WEEPING_VINES
- WET_SPONGE
- WHITE_CARPET
- WHITE_CONCRETE
- WHITE_CONCRETE_POWDER
- WHITE_GLAZED_TERRACOTTA
- WHITE_STAINED_GLASS
- WHITE_STAINED_GLASS_PANE
- WHITE_TERRACOTTA
- WHITE_TULIP
- WHITE_WOOL
- WITHER_ROSE
- WOODEN_AXE
- WOODEN_HOE
- WOODEN_PICKAXE
- WOODEN_SHOVEL
- WOODEN_SWORD
- YELLOW_CARPET
- YELLOW_CONCRETE
- YELLOW_CONCRETE_POWDER
- YELLOW_GLAZED_TERRACOTTA
- YELLOW_STAINED_GLASS
- YELLOW_STAINED_GLASS_PANE
- YELLOW_TERRACOTTA
- YELLOW_WOOL

