name: Block4Block
main: hasjamon.block4block.Block4Block
api-version: 1.16
authors: [ HasJamOn, Bahm, gtg_cya ]
version: 1.0
description: Block4Block plugin
commands:
  die:
    description: Use this command to kill yourself if you are stuck.
    usage: /<command>
    aliases: [suicide, kill]
  hints:
    description: Turns hints on/off.
    usage: /<command> [on|off]
  b4bhelp:
    description: Shows an inventory with items that explain how Block4Block works.
    usage: /<command>