name: Block4Block
main: hasjamon.block4block.Block4Block
api-version: 1.17
authors: [ HasJamOn, Bahm, gtg_cya ]
softdepend: [ProtocolLib]
version: 1.8
description: Block4Block plugin
commands:
  die:
    description: Use this command to kill yourself if you are stuck.
    usage: /<command>
    aliases: [suicide, kill]
  hints:
    description: Turns hints on/off.
    usage: /<command> [on|off]
  b4bhelp:
    description: Shows an inventory with items that explain how Block4Block works.
    usage: /<command>
    aliases: [helpb4b]
  ignore:
    description: Ignores a player to hide their messages until you use /unignore or for x minutes.
    usage: /<command> player [minutes]
  unignore:
    description: Removes a player from your ignore list to start showing their messages again.
    usage: /<command> player
  claimcontest:
    description: Everything you need to start a Chunk Claim Contest.
    usage: Invalid command, see correct usage with /<command> help
    permission: op
  bed:
    description: A free bed. Can only be used once every 24 hours.
    usage: /<command>
  welcome:
    description: Shows the welcome message.
    usage: /<command>